### ISSUE TITLE
Template loading error when attempting to use custom template

### ISSUE THREAD

**Issue by BigglesZX** [verbb/knock-knock#76]
### Question

Hi all,

Firstly, thanks for this plugin! ❤️ 

**Craft Pro** installation version **5.2.8**

I'm having an issue trying to use a custom template. The [docs](https://verbb.io/craft-plugins/knock-knock/docs/feature-tour/usage#custom-template) helpfully point to the original [password template](https://github.com/verbb/knock-knock/blob/craft-5/src/templates/ask.html) which I thought I would copy and make some minimal edits to (e.g. I wanted to add the site logo). I copied the `ask.html` template into my project as `templates/knock-knock/ask.twig` and made a couple of simple text edits to test. I was hoping to keep the existing template inheritance so that I didn't need to restyle the page.

However when loading the password view I get the following error:

```
Unable to find the template “_includes/forms” in "knock-knock/ask.twig" at line 2.
```

Commenting out that line, the error becomes:

```
Unable to find the template “_layouts/base” in "knock-knock/ask.twig" at line 1.
```

So it seems the template loader can't find either of those templates in the hierarchy. I think they are Craft internal templates rather than anything specifically to do with Knock Knock.

Weirdly if I try `{% extends "_layouts/cp.twig" %}` at the top of the template instead (per the Craft docs [here](https://craftcms.com/docs/5.x/extend/cp-templates.html#page-templates)) that doesn't work either, so I'm not sure if there's a more general issue with my template root settings. I do have one custom root registered by my own plugin:

```php
Event::on(View::class, View::EVENT_REGISTER_SITE_TEMPLATE_ROOTS, function (RegisterTemplateRootsEvent $e) {
    $e->roots['@components'] = __DIR__ . '/../../src/components';
});
```

...but as I understand it this should be additive and not affect existing roots.

I feel like I'm making some elementary mistake. Does anyone have any ideas?

Thanks!

**Comment by engram-design** [comment]
So yep, you unfortunately can't copy our template because it's loaded in the context of a control-panel template, where as if you supply your own template, it's loaded in the context of a site template. This is so that we can resolve _where_ your template actually exists. If we keep it in control-panel context, it's going to try and look for your template in Craft, a plugin or a module's files.

The difference is that our template uses those lines:

```
{% extends '_layouts/base' %}
{% import '_includes/forms' as forms %}
```

Which is loading Craft's `_layouts/base` and `_includes/forms` templates, which are only accessible when in "control panel" template mode - if that makes sense. It's getting into the intricacies of how Craft loads templates between site and control panel.

So _unfortunately_ for now, you'll have to write your template from scratch. I'll give this some thought and play around with some options to see if we can get this working how we'd like within a control panel context template.

**Comment by BigglesZX** [comment]
@engram-design Thanks for the quick reply Josh! That all makes sense. I had forgotten about the different template environments between the control panel and the site. It's not a biggie so I'm sure I can come up with a template from scratch if needed. Thanks again.
